name: blog_app
type: ruby:2.5
disk: 2048
relationships:
  database: "postgres_db:postgresql"
web:
    upstream:
       # Send requests to the app server through a unix socket, whose location
       # will be defined in an environment variable named SOCKET.
       socket_family: "unix"
    # Commands are run once after deployment to start the application process.
    commands:
       start: "puma -b unix://$SOCKET -e production config.ru"

    # The folder from which to serve static assets, for this location.
    #
    # This is a filesystem path, relative to the application root.
    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h
allow: true
hooks:
  build: |
    gem install bundler
    bundle install --without development test
  deploy: |
    RAILS_ENV=production rake db:migrate